export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const SET_CURRENT_PARKING = 'SET_CURRENT_PARKING'
export const REMOVE_CURRENT_PARKING = 'REMOVE_CURRENT_PARKING'

